### ISSUE TITLE
How to inject raw html? TrustedHTML?

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#11]
How can I inject raw html in a component's view?
I guess that TrustedHTML is the way to go, but I haven't figured out how to use it...

**Comment by benmerckx** [comment]
Yes, that's what it's there for. I haven't documented it though since I'm not happy with the way it works currently, meaning I'll probably change it later on. This how it can be used now:

``` haxe
(div > new TrustedHTML('<b>html</b>'))
```

I wanted something simple like Ithril.trust(...), but currently Ithril is an interface so that wouldn't work. Suggestions are welcome :)

**Comment by cambiata** [comment]
Thanx! 

TrustedHTML renders as expected on server (neko) but it doesn't seem to give any output on the client. When running the following, the server renders the `<h1>Trusted HTML</h1>` as expected, but when the client kicks in (2000 ms delay, just to see what happens), then the output is blank...

```
package;
import ithril.Component;
import ithril.TrustedHTML;
import haxe.Timer;

 typedef AppState = { origin:String, html:String, }

 class TrustedHtmlTester extends Component<String> {
    public function view() [
    (div)
        (div > new TrustedHTML(state))
        (div > '$state')
    ];
}

class Main extends Component<AppState>
{   
    public function view() [
        (p > '$state')
        (TrustedHtmlTester(state.html))
    ];

    public function layout() [
        (!doctype)
        (meta[charset="utf-8"])
        (link[href="style.css"][rel="stylesheet"])
        (body)
            [view()]
        (script+appstate > 'appstate="' + haxe.Serializer.run(state) + '"') 
        (script[src="mithril.js"])
        (script[src="client.js"])
    ];  

    static public function main() 
    {
        var main = new Main();

        #if sys
            var appState:AppState = { origin:'Server', html: '<h1>Trusted HTML</h1>' }; 
            main.setState(appState);
            Sys.print(ithril.HTMLRenderer.render(main.layout()));
        #else
                // On the client
            var appState:AppState = haxe.Unserializer.run(untyped appstate);
            appState.origin = 'Client';
            main.setState(appState);
            Timer.delay(function() {
                untyped m.mount(js.Browser.document.body, main);
            }, 2000);
        #end        
    }   
}

```

**Comment by benmerckx** [comment]
Can you check the console for errors? There's an annoying restriction in mithril which throws an error if you return an array in a component. The view function of your Main has this:

``` haxe
[
  (p > '$state')
  (TrustedHtmlTester(state.html))
]
```

Where mithril always expects only one root element like this:

``` haxe
[
  (div)
    (p > '$state')
    (TrustedHtmlTester(state.html))
]
```

Not sure if that's the actual problem here, but seems like it on first view.

**Comment by cambiata** [comment]
Ah, changing the view output to 

```
[
  (TrustedHtmlTester(state.html))
] 
```

did it! Thankx!

**Comment by cambiata** [comment]
Hm, I was fooled by wrong output when using mithril 0.2.1. (Using that particular version the client re-renders the body content below the server output - not removing server content first... Works fine in mithril 0.2.0 and 0.2.3)

Still no clientside output from ithril.TrustedHTML!

However, the hacked version below works for me. It adds an extra clientside span, but that's ok for me now.

```
package ithril;

class TrustedHTML {
    var body: String;

    public function new(body: String) {
        this.body = body;

        // #if js 
        // untyped return m.trust(body);
        // #end
    }

    // Works when adding the following view method:
    #if js
    @:keep public function view() { 
        return untyped m.m('span', m.trust(this.body)); 
    }
    #end

    public function toString() {
        return body;
    }
}

```

**Comment by benmerckx** [comment]
This has to do with the same mithril restriction. In mithril any 'component' (object/instance with a view method) must return a virtual element and cannot return an array, string, float, ..., null or trusted html as root. It's annoying and I don't check it in ithril because I'm hoping that limitation will go away. But I might have to clarify that in the docs for now. 

[Here's more info...](http://mithril.js.org/mithril.component.html#limitations-and-caveats)

> Nested component views must return either a virtual element or another component. Returning an array, a string, a number, boolean, falsy value, etc will result in an error.

**Comment by benmerckx** [comment]
Closing this as it should no longer be an issue with the new version.
