### ISSUE TITLE
How to redraw a component when state changes?

### ISSUE THREAD

**Issue by cambiata** [benmerckx/ithril#5]
Hi!

I'm experimenting with the simplistic autoupdating component below.
When the setInterval timer calls setState, I was expecting the view to re-render to reflect the new state. This doesn't happen. Should I kick off the re-rendering, or is there some other way of doing this? 

/ Jonas 

```
class SimpleCounter extends Component<Int> {
    public function view() [
        (div > this.state)
    ];

    override public function setState(state) {
        super.setState(state);
        trace(this.state);
    }

    override public function mount() {
        #if js
        js.Browser.window.setInterval(function() {
            this.setState(++this.state);
        }, 1000);
        #end
    }
}
```

**Comment by benmerckx** [comment]
Hi Jonas,

Thanks for trying out ithril! Because ithril uses mithril for rendering the views, any redrawing relies on using the mithril ecosystem. So in your example (if you're using the mithril externs) you'd call M.redraw() in your interval callback to redraw everything. Mithril will [redraw automatically](https://lhorie.github.io/mithril/auto-redrawing.html) if an event listener is called (for example onclick, onchange etc.) on one of the elements on which you have a listener attached.

I like the way mithril does redraws, the approach is very simple (diff everything when something changes) even though you'll have to call it yourself if anything changes outside of the event listeners or asynchronously. I might introduce a smarter system but for now any redraw calls should be handled using mithril. In the future I'd like to figure out if I can also map ithril over doom or react and that would mean a very different abstraction.

You can check out some [examples of components](https://github.com/benmerckx/ithril-elements/blob/gh-pages/web/Web.hx) I'm working on here: https://github.com/benmerckx/ithril-elements/tree/gh-pages/src/ithril/elements

Ben

**Comment by cambiata** [comment]
Thank you, Ben!

Using m.redraw(), I still must be missing something - still no re-rendering, the initial state value is unchanged. (Could this be related to ComponentCache or something..? Wild guess.)
Here's my code, with the Web class modelled from your Ithril-elements repo:

```
class SimpleCounter extends Component<Int> {
    public function view() [
        (div > this.state)
    ];

    /* override public function setState(state) {
        super.setState(state);
    } */

    override public function mount() {
        #if js
        js.Browser.window.setInterval(function() {
            var val = Math.round(Math.random() * 100);
            this.setState(val);
            trace(this.state);
            untyped m.redraw();
        }, 1000);
        #end
    }
}

class Web extends Component {
    public function view() [
        (title > 'Ithril Elements')
        (meta[charset="utf-8"])
        (meta[name="viewport"][content="width=device-width, initial-scale=1.0"])
        (link[href="assets/layout.css"][rel="stylesheet"])
        (body)
            [body()]
    ];

    @:access(ithril.component.ComponentCache)
    public function body() {
        [
            (h2 > 'Testing SimpleCounter:')
                (SimpleCounter(123))
        ];
    }   

    public static function main() {
        #if !js
        var html = HTMLRenderer.render([
            (!doctype)
            (html)
                (Web)
                (script[src="https://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.0/mithril.min.js"])
                (script[src="assets/main.js"])
        ]);
        Sys.println(html);
        #else
        untyped m.mount(js.Browser.document, new Web());
        #end
    }
}
```

**Comment by benmerckx** [comment]
Ok, I see the problem here. The state can and should not be changed inside components. It will be passed in on each redraw, so in your case SimpleCounter would always receive '123' and use that for rendering. Below you'll see a simple example of how you could make it work using the same interface (being `(SimpleCounter(123))`). I do however recommend not using it this way and instead making it very clear what the state will be used for. Because 123 is used as the initial value of your component instead of the actual count during rendering, a `Component<{initialValue: Int}>` would be more appropriate. Which would be used in a view like this: `(SimpleCounter (initialValue=123))`. 

Another way to go about this is making it possible to update the value in your parent `Component` by requiring an `onchange` method to be passed in which would update the counter wherever it originated from (and then setting the state accordingly). You can see how I'm doing that with `startFrom` in the input field below. If I did not update the value in the `oninput` listener, the value would never change.

Anyway, all of that doesn't really matter that much as you were simply trying to test it and I'm sure more real-world examples should be easier to create :) 

You can find a live example of the following [here](http://counter-ben.codeu.rs/):

``` haxe
import mithril.M;
import ithril.Component;

class SimpleCounter extends Component<Int> {
  var initial: Int;
  var count: Int;
  var interval: Int;

  public function view() [
    (div > count)
  ];

  override public function setState(state) {
    if (initial == state) return;
    count = initial = state;
    js.Browser.window.clearInterval(interval);
    interval = js.Browser.window.setInterval(function() {
      count++;
      M.redraw();
    }, 1000);
  }
}

class Web extends Component {
  var startFrom = 123;

  public function view() [
    (h2 > 'Testing SimpleCounter:')
      (SimpleCounter (startFrom))
    (div)
      ['Initial count: ']
      (input[type="number"] (value=startFrom, oninput=function(e) startFrom=e.target.value))
  ]; 

  public static function main() {
    M.mount(js.Browser.document.body, new Web());
  }
}
```

**Comment by cambiata** [comment]
Thank you, Ben, for a very clarifying example!

The setInterval thing in my simple component was just used for trying to understand the way state is handled, and what does kick off the rendering.
